### PR TITLE
Update typescript's definition

### PR DESCRIPTION
**Pull request by peleteiro**
Moving to es6/rollup made index.d.ts outdated.
Hope you find this pull request helpful. I ❤️StackBlur.

### CODE REVIEW

**Comment by brettz9** [comment]
Thanks for the contribution! Merged into `master`... May I ask how you use the definitions? For IDE autocomplete and such? I have yet to take the plunge into TS, despite using JSDoc...

**Comment by peleteiro** [comment]
When using typescript you must have definition for all libraries you use. Usually all of them have it or you can install using `npm install @types/[libname]`. Otherwise you must write it yourself.

I like TypeScript for bringing a useful type system to JS, IDE autocomplete/tooling (vscode/atom) and some errors checking.

I use StackBlur on my pet project https://www.biblebox.com - Using it:  !(https://cdn-std.dprcdn.net/files/acc_514552/Lxf3Jp)

**Comment by peleteiro** [comment]
You need to bump the version and release on NPM in order to this change be easily available. Could you mind release a patch version?

**Comment by brettz9** [comment]
I went with a minor version update due to the enhancements... Available now as part of 2.1.0... Thanks again for the PR...

**Comment by peleteiro** [comment]
Thank you very much!

**Comment by brettz9** [comment]
Happy to add just a little on top of @flozz's hard work...

**Comment by flozz** [comment]
I didn't do that much, it is based on the Mario Klingemann's algo and code, I just made few changes :)

**Comment by brettz9** [comment]
Hehe... Well, glad you made it available in the repo here and made those changes... :-)

**Pull request merged**
