### PR TITLE
Rollup, JSDocs, and fix for `instanceof`

### LINKED ISSUE #24: Problem with `instanceof` checks
Hi,

Great library!

Been doing a little retooling (for a PR on SVGEdit to allow our version of canvg to add as a module), mostly to convert to ES6 Modules, and I noticed your `instanceof` checks were off.

https://github.com/flozz/StackBlur/blob/master/src/stackblur.js#L85

has:

```js
else if (typeof HTMLImageElement !== 'undefined' && !img instanceof HTMLImageElement) {
```

You want `img instanceof HTMLImageElement` wrapped in parentheses here (and in the other 2 instances where this occurs) since otherwise the precedence will have `!` applied first to `img`, ensuring that this part of the expression will always render `true. In other words, your code always returns silently, even when an image element is provided (unless the previous block was reached by the user having supplied a string ID).

But for cross-frame support, not to mention easier Node support, you might want to avoid `instanceof` checks and just duck-type here, e.g., checking for the presence of `'naturalWidth' in img`.

Also FYI, with the netscape privilege code removed, you've been left with an extra try-catch block.

Brett

### PR DESCRIPTION
**Pull request by brettz9**
- Fix: Duck type with image or canvas in place of `instanceof` check (and a broken one; fixes #24)
- Enhancement: Add JSDoc comments
- Linting (ESLint): Add ESLint with "standard" base
- Linting (Markdown): Add .remarkrc
- Linting (package.json): Add recommended properties
- License: Change MIT license file name to reflect license type (MIT)
- Docs: Move changelog to own file: CHANGES.md
- Demo: Move demo to own directory (with static server to avoid Chrome security problems reaching out of folder)
- Demo: Move JS and CSS to separate files for easier linting/examination
- Build: Move from Grunt to Rollup, supporting ES6 Modules export
- Build: Remove now deprecated Bower
- Build: Add npm-recommended `package-lock.json`
- npm: Add start, eslint, rollup, open-docs, docs scripts
- npm: Add `module` for ES6 module discovery and switch `main` to point to `dist`

### CODE REVIEW

**Comment by eweitz** [comment]
@flozz, what are your thoughts on merging this PR?  A project I work on is migrating to the ES6 module system, and it seems merging this would enable ES6 export for StackBlur.

@brettz9, these improvements look great.  Thank you!

**Comment by brettz9** [comment]
Yes, it does allow for ES6 export--We're using it as such with SVG-Edit... Could we get a review or some feedback?

**Comment by brettz9** [comment]
If not a review, then perhaps Git/npm access if you're no longer maintaining... :-) I'd like to provide these improvements for their own sake, and also to draw them into canvg and SVG-Edit... Thanks!

**Comment by flozz** [comment]
Hello,

I delayed the review of this PR because it was big... and then I forget about it... sorry. Probably you are right, I have not enough time to maintain this library.... @brettz9 would you help me to maintain it, if yes, what is your NPM account?

**Comment by brettz9** [comment]
No worries! I definitely hear you on how that can happen... I appreciate it... My account is brettz9...

**Comment by flozz** [comment]
You should have the right to publish on NPM now, and you should be able to push on this repo too, let me know if there is any issue :)

**Comment by brettz9** [comment]
Great, thanks so much!

**Pull request merged**
