### PR TITLE
Consider node-canvas support

### PR DESCRIPTION
**Pull request by swhite24**
First, thanks for the great library!

Any interest in supporting node.js as well via [node-canvas](https://github.com/Automattic/node-canvas)?  I've altered the type checking on input `canvas` and `img` as these globals are not available.

Thanks!

### CODE REVIEW

**Comment by flozz** [comment]
Published in 1.4.0, thanks

**Comment by amilajack** [comment]
@swhite24 how can this be used with node-canvas now?

**Comment by swhite24** [comment]
@amilajack I've only used it via the `canvasRGBA` method, which can accept a `Canvas` instance from node-canvas.

For instance, here's how I'm able to blur an image from disk:
```javascript
import Canvas, { Image } from 'canvas';
import StackBlur from 'stackblur-canvas';
import fs from 'fs';

// Load image
const image_data = fs.readFileSync('img.png');
const input_img = new Image();
input_img.src = image_data;

// Setup canvas
const canvas = new Canvas(input_img.width, input_img.height);
const ctx = canvas.getContext('2d');
ctx.drawImage(input_img, 0, 0, input_img.width, input_img.height);

// Apply blur
StackBlur.canvasRGBA(canvas, 0, 0, input_img.width, input_img.height, 5);

// Write blurred image
canvas.pngStream().pipe(fs.createWriteStream('out.png'));
```

**Comment by amilajack** [comment]
@swhite24 I see. Thanks!

**Pull request merged**
